### ISSUE TITLE
链接404

### ISSUE THREAD

**Issue by lmislm** [cag2050/vue_tables_xlsx_demo#1]
https://njleonzhang.github.io/vue-data-tables/#/event?id=filtered-data

**Comment by cag2050** [comment]
此项目是基于 vue-data-tables 版本3.1.0，链接也是之前版本3.1.0的，后续此库版本、文档有更新，所以显示404；如果使用 vue-data-tables 的其他版本，代码可能需要自己根据具体版本进行调整。
